### ISSUE TITLE
NOT LOADABLE: name 'CJK' is not defined

### ISSUE THREAD

**Issue by coiby** [pediapress/mwlib.rl#3]
According to pdfstyles.py, "set to CJK if a PDF is rendered mainly using chinese, japanese or korean glyphs". But if I set word_wrap to "CJK" or "RTL", "name 'CJK'/'RTL' is not defined in function system" will be given. And "mw-render --list" shows:
odf OpenDocument Text
rl  <NOT LOADABLE: name 'CJK' is not defined>

**Comment by v0lk3r** [comment]
The comment you reference might not be 100% clear, but you need to do the following:

word_wrap = 'CJK' 

and not word_wrap = CJK.

And: normally it should not be required at all to manually set the word_wrap variable. If the proper language is used (when rendering) the pdf export software should automatically choose the correct word_wrap value.

**Comment by coiby** [comment]
I see. I just read the style file and change it according the instruction. Thanks!
